# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af0371774716fbbe0a3fe8b7b579fabd13a4ff0e840898be71442a28f99538945c2dc69045b270ff57370e65d709ab7a068a8352f6a7fc9a7809c2a3f23b460c

test:
  secret_key_base: 6faef62e218b7fdb0413fd37336ab6c41fc39a91c7cdd464e48106fef494053169490a48e448bfbff6df4d074b08442d296e706edd3c95b5e69a53bef9bdc2bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
